spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    userId: sa
    password: password
  hibernate:
    ddl-auto: update
openai:
  api-key: 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